name: Python application

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -f docker/Dockerfile -t api .

      - name: Run tests
        run: docker run -t api pytest
